function skillsMember() {
    return [
        {name: 'HTML', level: 10},
        {name: 'CSS', level: 10},
        {name: 'JavaScript', level: 10},
        {name: 'React', level: 10},
        {name: 'Node', level: 10},
        {name: 'MongoDB', level: 10},
        {name: 'Express', level: 10},
        {name: 'Python', level: 8},
        {name: 'Django', level: 8},
        {name: 'PostgreSQL', level: 8},
        {name: 'SQL', level: 8},
        {name: 'Git', level: 10},
        {name: 'Docker', level: 8},
        {name: 'Jenkins', level: 8},
        {name: 'Kubernetes', level: 8},
        {name: 'AWS', level: 8},
        {name: 'GCP', level: 8},
        {name: 'Azure', level: 8},
        {name: 'Linux', level: 8},
        {name: 'Windows', level: 8},
        {name: 'MacOS', level: 8},
        {name: 'C', level: 8},
        {name: 'C++', level: 8},
        {name: 'Java', level: 8},
        {name: 'Ruby', level: 8},
        {name: 'Go', level: 8},
        {name: 'Swift', level: 8},
        {name: 'Kotlin', level: 8},
        {name: 'Flutter', level: 8},
        {name: 'React Native', level: 8},
        {name: 'Android', level: 8},
        {name: 'iOS', level: 8},
        {name: 'Angular', level: 8},
        {name: 'Vue', level: 8},
        {name: 'Svelte', level: 8},
        {name: 'Next', level: 8},
        {name: 'Nuxt', level: 8},
        {name: 'Gatsby', level: 8},
        {name: 'Hugo', level: 8},
        {name: 'Jekyll', level: 8}
    ]};